Repository jupyterhub/pebble-helm-chart, pull requests merged in 2022-03, with the labels that each got.

#11 readinessProbe to do nothing more than needed
  pebble/templates/pebble-deployment.yaml
Labels: bug

#14 ci/docs: 2022 refresh of this repo
  .github/dependabot.yaml
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  DEVELOPMENT_HISTORY.md
  README.md
  chartpress.yaml
  ci/publish
  pebble/templates/pebble-configmap.yaml
  pebble/templates/pebble-deployment.yaml
  pebble/templates/tests/coredns-pod.yaml
  pebble/templates/tests/pebble-pod.yaml
  pebble/values.schema.json
  pebble/values.yaml
Labels: documentation, ci

#12 Update pebble version from 2.3.0 to 2.3.1
  pebble/Chart.yaml
Labels: dependencies, maintenance
